name: ci-toaster-eats

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./app

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@latest

      - name: Cache node modules
        uses: actions/cache@latest
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-v5-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@latest
        with:
          node-version: '16.x' # or specify the version you need

      - run: npm ci --legacy-peer-deps

      - run: curl https://install.meteor.com/ | sh

      - name: Run Meteor commands
        shell: bash -l {0}
        run: |
          meteor npm install
          meteor npm run lint
          meteor npm run testcafe-ci

